### ISSUE TITLE
 No such file or directory: 'test_pddlstream.py'

### ISSUE THREAD

**Issue by roshandhakal** [Learning-and-Intelligent-Systems/kitchen-worlds#9]
So, I am testing test_pddlstream.py currently and there's no test_pddlstream.py file inside the tests folder. Or, is it in some other directory?

**Comment by zt-yang** [comment]
Hi, Roshan, it was moved to the `pybullet_planning/tests/` directory: https://github.com/zt-yang/pybullet_planning/tree/194dc36476e540c4e5a03f03c712d213aa680416/tests

**Comment by roshandhakal** [comment]
Hi Zhutian, the example test_pddlstream seems to have some errors and I couldn't correct them. Is there something I am missing?

**Comment by zt-yang** [comment]
May I see the error message? I meant to test the scripts for the paper code release but was delayed by the paper rebuttal this week. If we can't resolve the problem today quickly, I'll get back to you around Thur with tested code and updated instructions.

**Comment by roshandhakal** [comment]
First of all, the main branch does not have test_cases to begin with for test_pddlstream to load up pddl and lisdf files. I was trying to run pr2_kitchen. Secondly, planning_config.json seems to be incomplete. Also, there are few attribute errors like: AttributeError: 'World' object has no attribute 'robot', which also prevented running test_data_generation.

**Comment by zt-yang** [comment]
Ok, thank you for reporting these issues. I'll update those test files to make sure it works for you by the end of Fri, Aug 11. Would that be helpful to you?

**Comment by roshandhakal** [comment]
Sure absolutely. Thank you very much.

**Comment by roshandhakal** [comment]
Hi Zhutian, any update on this? Thanks

**Comment by zt-yang** [comment]
Hi Roshan, thank you for reaching out. I'm sorry my hands are tight with the CoRL rebuttal which will be done on Wed. Unexpected experiments came up and I won't be able to get back to this issue until this Thursday. Are you in urgent need of the code (ICRA/ICLR deadline)? If you can tell me more about your intended usage of the codebase, I can focus on getting those working first and point you to the configuration files to modify for your tasks.

**Comment by roshandhakal** [comment]
Hi Zhutian, please take your time and be done with the CoRL thing first. Good luck. You can get back to working on it at your convenience.

**Comment by zt-yang** [comment]
Hi Roshan, thank you for your understanding! I'll update you on this soon.

**Comment by roshandhakal** [comment]
Hi, any update on this?

**Comment by zt-yang** [comment]
Hi Roshan, thank you for your patience. The problem has been fixed. Pull both kitchen-worlds and kitchen-worlds/pybullet_planning then run again. Let me know if you have other questions :)

**Comment by roshandhakal** [comment]
Hi Zhutain, thank you so much for your time and effort. I am still getting following error. The planning_config.py does not have "domain_full" param. Should be easy fix but I am not sure where I change it.
![image](https://github.com/Learning-and-Intelligent-Systems/kitchen-worlds/assets/30138013/1d7fbead-eabc-4e48-a3ab-b123895a165d)

**Comment by zt-yang** [comment]
Hi Roshan, have you pulled `kitchen-worlds/pybullet_planning` ?

On Sep 3, 2023, at 11:15, Roshan Dhakal ***@***.******@***.***>> wrote:



Hi Zhutain, thank you so much for your time and effort. I am still getting following error. The planning_config.py does not have "domain_full" param. Should be easy fix but I am not sure where I change it.
[image]<https://user-images.githubusercontent.com/30138013/265272759-1d7fbead-eabc-4e48-a3ab-b123895a165d.png>
